### ISSUE TITLE
Library deduplication

### ISSUE THREAD

**Issue by dvoytenko** [cloudflare/workers-web-experiments#33]
Following this project from https://blog.cloudflare.com/better-micro-frontends. Very interesting... It mentions "tree-shaking", but doesn't quite explain if this is part of the architecture? E.g. can two fragments share a library with a state?

**Comment by petebacondarwin** [comment]
Hi @dvoytenko - thanks for your interest in the project.

As it stands each fragment must be self-contained. They do not share any code on the client.

One of the benefits of this approach is that by fragments not sharing code, we know at build/SSR time, exactly what code is needed for that fragment, and so can remove any unused code.

As soon as you have a library that is shared between fragments you must either:

a) end the entire library down to the client, just in case there is a fragment that needs it, or
b) do some kind of global analysis of all the fragments at build time to work out if there is any code that can be removed

Even in the second case we might end up sending unused code, since you would have to send down all the code that might be possibly used, even if some fragment is never actually displayed to a user.

The Qwik framework goes even further and only requires code (even within a fragment) to be downloaded if that bit of functionality is going to be used. This has the effect of reducing the client-side code to the bare minimum.

One downside of this isolated approach to client-side code, is that if two fragments need to use the same client-side code, it gets downloaded and executed twice. Imagine this could be the case for a standard library of widgets (buttons, drop-downs, date-pickers, etc). So there is a trade-off involved.

But the argument is that (especially with HTML first frameworks like Qwik) that the duplication is localised to the pieces of the HTML that need to be "resumed" (i.e. that the user interacts with). If there are large parts of the app that use such widgets, but are not interacted with, then the client-side code for these fragments would not need to be downloaded.

I can imagine, though, some ways to mitigate these problems. For example, Qwik will attach a SHA to each client-side code file it generates. If there is an identical block that is used by multiple fragments, then it would have the same SHA and so we could avoid downloading it twice? Note that this is a hand-wavy idea right now, since the way that Qwik breaks up blocks of code is opaque and probably case-specific.
